RD-6693 Skip first line of the traceback
The `dispatch.py` cruft is not interesting for the user. We can make
the tracebacks a bit more useful by removing it.

Before:
```
Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python3.10/site-packages/cloudify/dispatch.py", line 337, in _execute_workflow_function
    workflow_output = self.func(*self.args, **self.kwargs)
  File "/opt/mgmtworker/env/lib/python3.10/site-packages/cloudify_system_workflows/deployment_environment.py", line 268, in create
    _check_blueprint_requirements(ctx, deployment, bp)
  File "/opt/mgmtworker/env/lib/python3.10/site-packages/cloudify_system_workflows/deployment_environment.py", line 222, in _check_blueprint_requirements
    raise ValueError(
ValueError: Environment env does not have the required capabilities: cap1.key1.0
```

After:
```
File "/opt/mgmtworker/env/lib/python3.10/site-packages/cloudify_system_workflows/deployment_environment.py", line 268, in create
  _check_blueprint_requirements(ctx, deployment, bp)
File "/opt/mgmtworker/env/lib/python3.10/site-packages/cloudify_system_workflows/deployment_environment.py", line 222, in _check_blueprint_requirements
  raise ValueError(
ValueError: Environment env does not have the required capabilities: cap1.key1.0
```