CommandExecutionException: handle unicode message (#442)
The message has to be unicode, because parts of it can be unicode.
And there's no reason to have bytes there anyway.

Also, drop the __str__, because that's the same as using the
baseclass one